version: "3.9"

services:
  elasticsearch:
    build:
      dockerfile: Dockerfile
      context: ./
      target: elasticsearch
    container_name: elasticsearch
    restart: always
    networks:
      - me_network
    ports:
      - 9100:9200
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
      - .:/elasticsearch-analysis-thaichub2
    command: sh -c './bin/elasticsearch-plugin install --batch file:///elasticsearch-analysis-thaichub2/target/releases/analysis-thaichub2-7.14.1.zip && exec /usr/local/bin/docker-entrypoint.sh elasticsearch'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.40'
    #       memory: 450M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 17M
    
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.14.1
  #   container_name: kibana
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601
  #   links:
  #     - elasticsearch:elasticsearch

networks:
  me_network:
volumes:
  elasticsearch-volume:
